staging: Include qcacld-3.0 source
* Also remove Android.mk as it overwrites our
  kernel source path.

Change-Id: I62bfae9bc90b900be380141f7567c70af4c075bf

Add 'drivers/staging/fw-api/' from commit 'c0b490045a8b5846735acbdcac93ecb03863fc7a'

git-subtree-dir: drivers/staging/fw-api
git-subtree-mainline: 73c04b1f66d8f209fac35da06cd5a0bb4420b770
git-subtree-split: c0b490045a8b5846735acbdcac93ecb03863fc7a

Add 'drivers/staging/qca-wifi-host-cmn/' from commit 'fb375b10c17f409a95416cdb4eb092a26349418c'

git-subtree-dir: drivers/staging/qca-wifi-host-cmn
git-subtree-mainline: d5dfb13a546040e85aeb7ef11e06fff79497dd03
git-subtree-split: fb375b10c17f409a95416cdb4eb092a26349418c

Add 'drivers/staging/qcacld-3.0/' from commit '8e45a23bb17abd275ebed15500a82eed3327f4af'

git-subtree-dir: drivers/staging/qcacld-3.0
git-subtree-mainline: 9dff4ef0d2fb52533b1f2c744cf18f366ec56a91
git-subtree-split: 8e45a23bb17abd275ebed15500a82eed3327f4af

qcacld-3.0: Disable build timestamp

Change-Id: I8b917928671f14caedf2401eeb92ea07a184f351
Signed-off-by: Danny Lin <danny@kdrag0n.dev>

qcacld-3.0: nuke Kconfig-based configuration entirely

This method of building qcacld isn't meant to be used and
causes conflicts with the new OEM profile configuration.

Configuration is now done with drivers/staging/qcacld-3.0/configs.

Signed-off-by: Park Ju Hyung <qkrwngud825@gmail.com>

qcacld-3.0: discard wlan_boot sysfs code on !CONFIG_MODULES

Change-Id: Ib659d0beab12e9fb6dcd80138fe1b31668d42afe
Signed-off-by: Park Ju Hyung <qkrwngud825@gmail.com>
Signed-off-by: Danny Lin <danny@kdrag0n.dev>

qcacld-3.0: defer hdd initialization and rely on userspace writing to /dev/wlan

Wi-Fi HAL writes "ON" or "OFF" to /dev/wlan.

Use this method to initialize hdd as it's a safer way to ensure both
wlan_mac.bin and WCNSS_qcom_cfg.ini is ready to be read.

This also eliminates the needs for horrible hack to read userspace file.

Change-Id: I3b0a8f5b8fc14e06c8bd3976d504382b226ada30
Signed-off-by: Park Ju Hyung <qkrwngud825@gmail.com>
Signed-off-by: Danny Lin <danny@kdrag0n.dev>

qcacld-3.0: default_config: tone down debugging

Change-Id: I29c3212f9a9d1b2be2cc456c40c338b465923071
Signed-off-by: Park Ju Hyung <qkrwngud825@gmail.com>
Signed-off-by: Danny Lin <danny@kdrag0n.dev>

qcacld-3.0: Nuke as much debug bloat as possible

The overhead from all the debugging in this monstrosity of a driver is
measurably significant. Chop it all out.

Signed-off-by: Sultan Alsawaf <sultan@kerneltoast.com>
[kdrag0n: adapted for Pixel 3 Wi-Fi stack]
Signed-off-by: Danny Lin <danny@kdrag0n.dev>

Adapted for qcacld 5.2.03

Change-Id: I6917d2f912cc1def45e984aa83d422fd2036e2dc
Signed-off-by: Park Ju Hyung <qkrwngud825@gmail.com>
Signed-off-by: Danny Lin <danny@kdrag0n.dev>

qcacld-3.0: disable bunch of more debug configs

These hurt performance

Change-Id: I732266debb5f88982e6c29a40b2533b5ae5d1478
Signed-off-by: Park Ju Hyung <qkrwngud825@gmail.com>
Signed-off-by: Danny Lin <danny@kdrag0n.dev>

qcacld-3.0: check if auth_tag_len exceeds sizeof(hash)

Without this check, memcmp() compile-time check fails

Change-Id: I9e51d13381a0c4ecba0a31965100423aa165897f
Signed-off-by: Park Ju Hyung <qkrwngud825@gmail.com>
Signed-off-by: Danny Lin <danny@kdrag0n.dev>

qcacld-3.0: nuke rx_wakelock code entirely

We're not allowing this to be configurable on this kernel.

Nuke this entirely to reduce resource usage.

Change-Id: I55e91eff39a562e77560803439af32ae19f4dd6d
Signed-off-by: Park Ju Hyung <qkrwngud825@gmail.com>
Signed-off-by: Danny Lin <danny@kdrag0n.dev>

qcacld-3.0: Guard WLAN_DEBUG functions subsequent to LA.UM.8.9.r1-08400-SM6xx.0 merge

This silences the following compilation errors:

../drivers/staging/qcacld-3.0/core/sap/src/sap_fsm.c:2748:51: error: use of undeclared identifier 'msg'
        sap_debug("state=%d handle event=%d", state_var, msg);
                                                         ^
../drivers/staging/qcacld-3.0/core/sap/src/sap_module.c:1320:10: error: implicit declaration of function 'sap_get_csa_reason_str' [-Werror,-Wimplicit-function-declaration]
                       sap_get_csa_reason_str(sapContext->csa_reason),
                       ^

Signed-off-by: Adam W. Willis <return.of.octobot@gmail.com>
Signed-off-by: Adithya R <radithya2002@gmail.com>

qcacld-3.0: Disable WMI history dumps on hang recovery

This feature depends on CONFIG_WMI_INTERFACE_EVENT_LOGGING, which we
have disabled.

Signed-off-by: Danny Lin <danny@kdrag0n.dev>